### ISSUE TITLE
docker 高级使用方式

### ISSUE THREAD

**Issue by sandshaw** [TarsCloud/TarsFramework#117]
docker 高级使用方式的基础镜像怎么生成？使用TarsDocker的basedocker？

**Comment by ruanshudong** [comment]
啥意思?

**Comment by sandshaw** [comment]
Tars文档中，[框架部署]-->[TarsDocker 部署]-->[8 docker 高级使用方式]的 “但是新版(tarsframework>v3.0.4, tarsweb>v2.4.25, tarscloud/framework>v3.0.5)的版本, 业务可以以独立容器运行, 此时需要在 tarsweb 运维管理->镜像管理中配置仓库和**_基础镜像_**, 然后服务配置中设置为以容器方式运行即可, 这样每个服务都可以运行在独立的容器中.“ 
这里的基础镜像是？

**Comment by ruanshudong** [comment]
这个你稍微等等, 这两天会出一个稍微详细的文档, 到时候贴给你.

**Comment by sandshaw** [comment]
好的，谢谢
