### ISSUE TITLE
 tarsregistry 服务在执行 replace into t_registry_info (locator_id, servant, endpoint, last_heartbeat, present_state, tars_version)  有时候会出现 Deadlock found when trying to get lock; try restarting transaction, please check!  

### ISSUE THREAD

**Issue by tomtry12** [TarsCloud/TarsFramework#126]

**Comment by tomtry12** [comment]
Version:2.4.10

**Comment by tomtry12** [comment]
在没有部署slave的时候未发现此问题

**Comment by tomtry12** [comment]
web:3.0.1
framework:3.0.7 
升级后还是会出现这个问题

**Comment by tomtry12** [comment]
![Uploading image.png…]()

**Comment by tomtry12** [comment]
![Uploading 企业微信截图_16553586856991.png…]()

**Comment by ruanshudong** [comment]
这个问题其实没啥影响, framework:v3.0.8应该也修改了这个问题

**Comment by tomtry12** [comment]
有点奇怪， 我拉的镜像也是 tarscloud/framework:v3.0.8 , 但启动后，web界面上显示的是 framework:3.0.7

**Comment by ruanshudong** [comment]
这里是有误解,  因为docker镜像的版本其实是Tars这个git的tag(因为包含了framework和web两个), web页面上限制的framework才是TarsFramework的tag

**Comment by tomtry12** [comment]
> 这里是有误解, 因为docker镜像的版本其实是Tars这个git的tag(因为包含了framework和web两个), web页面上显示的framework才是TarsFramework的tag

了解了谢谢，我重新pull 了 tarscloud/framework:v3.0.9  ,启动后是 framework:3.0.8 了

**Comment by tomtry12** [comment]
我从2版本升级到3版本后，原来2版本创建的user 无法登陆了，会提示密码错误，我看 请求里的登陆密码和数据库里的密码是一样的。   （在3版本重新创建的用户登陆是正常的 , 登陆时密码和数据库里不一样）
