### ISSUE TITLE
【tarscloud/tars.tarsweb:v1.4.0】admin->用户中心->Token管理->新增Token，报错：

### ISSUE THREAD

**Issue by Degfy** [TarsCloud/TarsFramework#131]
![image](https://user-images.githubusercontent.com/15191087/205883659-fdb45e5b-28b5-4a3b-9b45-ecbd40507b1a.png)
![image](https://user-images.githubusercontent.com/15191087/205883754-f42e50ad-bd71-4b4d-9e2e-8cac70308fd5.png)
**查了代码，"tarscloud/tars.tarsweb:v1.4.0" 镜像中的代码 有问题**:  
**前端传的数据格式为： {"expire_time":"2025-12-06"}**
**看后端代码，需要传  {"expire_time":"2025-12-06 00:00"}**

**Comment by Degfy** [comment]
@ruanshudong, 麻烦更新一下镜像吧？

**Comment by ruanshudong** [comment]
你把时间也选择一下呢?

**Comment by Degfy** [comment]
试了一下，选择了时间可以

> 你把时间也选择一下呢?
