### ISSUE TITLE
编译报 cannot stat 'tars.lex.cpp': No such file or directory

### ISSUE THREAD

**Issue by cat160** [TarsCloud/TarsFramework#15]
系统：centos7
mysql: 5.6.26
编译报错：
Linking CXX static library ../lib/libtarsutil.a
Built target tarsutil
Scanning dependencies of target COPY-LEX-YACC
flex TarsFramework/tarscpp/tools/tarsgrammar/tars.l
cp -rf tars.lex.cpp TarsFramework/tarscpp/tools/tarsparse
cp: cannot stat 'tars.lex.cpp': No such file or directory
make[2]: *** [../tarscpp/tools/tarsparse/tars.lex.cpp] Error 1
make[1]: *** [tarscpp/tools/tarsgrammar/CMakeFiles/COPY-LEX-YACC.dir/all] Error 2
make: *** [all] Error 2

**Comment by ETZhangSX** [comment]
你好，请问这个问题还存在吗？是必现吗？

**Comment by cat160** [comment]
必现，代码克隆下来，按文档编译，就会报这个错误

**Comment by ETZhangSX** [comment]
可以提供一下你使用环境的前置依赖的版本号吗？包括比如`Linux`内核 ,`gcc`, `bison`, `flex`, `cmake` 等的版本

**Comment by cat160** [comment]
linux: 3.10.0-862.el7.x86_64  centos7.5
gcc: 4.8.5
cmake: 2.8.8
node: 8.11.3
npm: 5.6.0
bison: 3.0.4
flex: 2.5.37

**Comment by ruanshudong** [comment]
手工运行:
flex TarsFramework/tarscpp/tools/tarsgrammar/tars.l

看看是否报错
