### ISSUE TITLE
NodeServer模块启动java程序是否要加个&符号？

### ISSUE THREAD

**Issue by jhhe66** [TarsCloud/TarsFramework#22]
NodeServer->CommandStart.h的376行，我之前部署java，总是失败，后来发现少了个&，加上就部署成功了。
修改前：osStartStcript << _exeFile << " " << TC_Common::tostr(vOptions) << endl;

修改后：osStartStcript << _exeFile << " " << TC_Common::tostr(vOptions) << " &" << endl;

**Comment by ruanshudong** [comment]
fork出来的, 按说不需要这个符号, 确认有这个问题?

**Comment by jhhe66** [comment]
试了很多次，加上这个就可以正常运行了。

**Comment by ruanshudong** [comment]
bug fix
