### ISSUE TITLE
linux-install.sh 获取IP异常

### ISSUE THREAD

**Issue by isharecode** [TarsCloud/TarsFramework#26]
系统：Ubuntu 16.04 LTS
linux-install.sh 的 get_host_ip 里的 
IP=`ifconfig | grep $1 -A3 | grep inet | awk -F':' '{print $2}' | awk '{print $1}'`
会获取到 IPv6 的地址头，fe80。导致 fe80 作为参数参入 tars-install.sh 里的 REBUILD

![微信截图_20191212142658](https://user-images.githubusercontent.com/6657358/70688536-fcf51080-1cec-11ea-8031-d34233483489.png)

**Comment by ruanshudong** [comment]
截图貌似看不见呢

**Comment by ruanshudong** [comment]
已经修改, ubuntu16.04  & ubuntu:18.04 都已经支持.
