### ISSUE TITLE
findObjectById(const string & id, tars::TarsCurrentPtr current);中的id是servant name吗？

### ISSUE THREAD

**Issue by mobihe** [TarsCloud/TarsFramework#54]
/** 
     * 根据id获取所有该对象的活动endpoint列表
     */
    virtual vector<EndpointF> findObjectById(const string & id, tars::TarsCurrentPtr current);

这里的id是servant name(xxx.xxx.xxxobj)样式的吗？
函数能正常返回吧？

**Comment by ruanshudong** [comment]
对
