### ISSUE TITLE
web扩容报错

### ISSUE THREAD

**Issue by Neil-Tz** [TarsCloud/TarsFramework#71]
我在扩容时启用了set，set_group有做修改，之后扩容有报错。
![image](https://user-images.githubusercontent.com/10428412/93840609-8e090700-fcc3-11ea-8d0e-24118bfbb0e9.png)
![image](https://user-images.githubusercontent.com/10428412/93840619-97926f00-fcc3-11ea-983f-4443829092b9.png)

**Comment by ruanshudong** [comment]
修复这个问题了, 请升级tarsweb到新版本
