### ISSUE TITLE
tars使用脚本启动成功判断结果永远是成功，if(_serverObjectPtr->savePid())，savePid()返回默认值是-1，导致判断永远是true。

### ISSUE THREAD

**Issue by zhangchengtan** [TarsCloud/TarsFramework#77]
在使用TarsFramework 2.4.9版本时，发现在使用脚本启动程序时，程序判断逻辑总是返回成功的，个人觉得这个应该有问题，导致使用脚本启动都是成功状态。目前解决方法将 int64_t iPid = -1;调整为  int64_t iPid = -0;进行解决。
![获取启动成功的pid信息代码](https://user-images.githubusercontent.com/8357895/98643910-a49a1900-236a-11eb-865a-1ebd489186a4.png)
![是否启动成功判断逻辑](https://user-images.githubusercontent.com/8357895/98643916-a6fc7300-236a-11eb-882d-7904b7466e0c.png)

**Comment by ruanshudong** [comment]
确实有问题, 提交一个pr?
