### ISSUE TITLE
通过TarsTimeLogger::getInstance()->enableRemote()设置禁止远程日志后，再调用TarsTimeLogger::getInstance()->initFormat()，会使得之前的禁止远程日志设置失效，这是正常的吗？

### ISSUE THREAD

**Issue by IT-Financial** [TarsCloud/TarsFramework#83]
我在根据TarsDoc学习的时候发现，关于DLOG/FDLOG的使用，存在以下疑问：
1) 按照官方的代码示例，先调用TarsTimeLogger::getInstance()->enableRemote("", false); 后调用
TarsTimeLogger::getInstance()->initFormat("", "%Y%m%d%H%M"); 远程日志和本地日志都会同时生成，即禁止远程日志设置失效；
2) 后来自己调整调用顺序，先调用TarsTimeLogger::getInstance()->initFormat("", "%Y%m%d%H%M"); 再调用TarsTimeLogger::getInstance()->enableRemote("", false); 可以实现禁止远程日志；后来通过阅读框架代码发现，每次调用initFormat(）的时候，都会调用一次initTimeLogger()，在initTimeLogger()函数里面会重新设置远程日志格式。通过 pTimeLogger->getWriteT().enableRemote(_remote)  会重新设置为可生成远程日志，因为RemoteTimeLogger对象的_remote成员变量好像只在构造函数中初始化为true。
3) 想问一下，DLOG/FDLOG 是应该先initFormat，再enableRemote的吗？还是说，这是一个bug；如果是框架设计如此，建议修改一下demo代码
4) 具体代码示例路径如下：
TarsDoc-->TarsCPP--> 使用指南--> 8.3. 代码示例

**Comment by ruanshudong** [comment]
使用上, 应该都是需要先init, 在enable才对
