### ISSUE TITLE
在编译c++开发环境时，编译错误，请教一下这个怎么干

### ISSUE THREAD

**Issue by text88888** [TarsCloud/TarsFramework#84]
[root@VM-0-9-centos build]# make -j4
[  3%] Built target ADD_mysqlclient
[  5%] Built target ADD_gtest
[  6%] Built target COPY-LEX-YACC
[  6%] Built target thirdparty
[ 27%] Built target tarsutil
[ 30%] Built target tarsparse
[ 30%] Built target tarsmerge
[ 31%] Built target tars2cpp
[ 32%] Built target tars2python
[ 34%] Built target tars2cs
[ 35%] Built target tars2c
[ 36%] Built target tars2oc
[ 37%] Built target tars2php
[ 39%] Built target tars2android
[ 39%] Built target TUP-TARS
[ 40%] Built target tars2case
[ 46%] Built target tars2node
[ 55%] Built target COPY-SERVENT-TARS
[ 57%] Built target FRAMEWORK-PROTOCOL
[ 57%] Building CXX object tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/Communicator.cpp.o
[ 57%] Building CXX object tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/Current.cpp.o
[ 57%] Built target patch
[ 57%] Building CXX object tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/EndpointInfo.cpp.o
[ 58%] Building CXX object tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/EndpointManager.cpp.o
[ 58%] Building CXX object tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/Global.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/EndpointManager.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/all] Error 2
make: *** [all] Error 2
[root@VM-0-9-centos build]# ^C
[root@VM-0-9-centos build]# c++: internal compiler error: Killed (program cc1plus)
-bash: syntax error near unexpected token `('
[root@VM-0-9-centos build]# Please submit a full bug report,
-bash: Please: command not found
[root@VM-0-9-centos build]# with preprocessed source if appropriate.
-bash: with: command not found
[root@VM-0-9-centos build]# See <http://bugzilla.redhat.com/bugzilla> for instructions.
-bash: http://bugzilla.redhat.com/bugzilla: No such file or directory
[root@VM-0-9-centos build]# make[2]: *** [tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/EndpointManager.cpp.o] Error 4
-bash: make[2]:: command not found
[root@VM-0-9-centos build]# make[2]: *** Waiting for unfinished jobs....
-bash: make[2]:: command not found
[root@VM-0-9-centos build]# make[1]: *** [tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/all] Error 2
-bash: make[1]:: command not found
[root@VM-0-9-centos build]# make: *** [all] Error 2^C

**Comment by ruanshudong** [comment]
升级cpu吧, 机器太差了

**Comment by aiyogg** [comment]
> 升级cpu吧, 机器太差了

在低配的腾讯云服务器上试着编译安装也遇到这个问题，搜了下应该是内存不够的原因。可以尝试给机器[加 swap](https://askubuntu.com/questions/33697/how-do-i-add-swap-after-system-installation/796997#796997)再试试

**Comment by Keeyuu** [comment]
确定是内存原因吗,为什么在64g,32g机器上也会有这个问题

**Comment by Keeyuu** [comment]
> 确定是内存原因吗,为什么在64g,32g机器上也会有这个问题
3.0.12版本没有任何问题,3.0.12 往上都会有同样的问题,使用的是Ubuntu20.04 22 都会有这个问题
我换了几台机器构建3.0.13 版本都会出这个问题/home/anyhow/TarsFramework/tarscpp/servant/servant/AdminF.h:652:29: note:       ‘virtual tars::Int64 tars::AdminF::getPid(tars::TarsCurrentPtr)’
  652 |         virtual tars::Int64 getPid(tars::TarsCurrentPtr _current_) = 0;
      |                             ^~~~~~
[ 60%] Building CXX object tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/BaseNotify.cpp.o
[ 60%] Building CXX object tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/Communicator.cpp.o
make[2]: *** [tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/build.make:115: tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/Application.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1847: tarscpp/servant/libservant/CMakeFiles/tarsservant.dir/all] Error 2
