### ISSUE TITLE
tarsRegistry 更新registry信息到db发生mysql Deadlock

### ISSUE THREAD

**Issue by MarsDy** [TarsCloud/TarsFramework#88]
ERROR:10.33.28.121: registry error: CDbHandle::updateRegistryInfo2Db:[TC_Mysql::execute]: mysql_query: [ replace into t_registry_info (locator_id, servant, endpoint, last_heartbeat, present_state, tars_version) values ('10.33.28.121:17890', 'AdminObj', 'tcp -h 127.0.0.1 -p 17890 -t 3000', now(), 'active', '2.4.10'), ('10.33.28.121:17890', 'tars.tarsregistry.QueryObj', 'tcp -h 10.33.28.121 -p 17890 -t 60000', now(), 'active', '2.4.10'), ('10.33.28.121:17890', 'tars.tarsregistry.RegistryObj', 'tcp -h 10.33.28.121 -p 17891 -t 60000', now(), 'active', '2.4.10') ] :Deadlock found when trying to get lock; try restarting transaction, please check!

**Comment by MarsDy** [comment]
tarsframework版本:2.4.9
OS:linux

**Comment by ruanshudong** [comment]
这个问题已知, mysql兼容性的问题 ,对业务无影响, 暂时未修改
